### PR TITLE
Fix for correctly escaping the " \ " character when converting an HTML template into a string.

### PR DESCRIPTION
**Pull request by intervalia**
I tried to add a pattern attribute to some new HTML and found that the HTML to string code did not correctly escape the \ character. This is now fixed.

### CODE REVIEW

**Comment by intervalia** [comment]
Not ready yet. I messed up something. I will fix it and let you know when it is done.

**Comment by intervalia** [comment]
Local tests now pass. This is ready to be pulled.

I have no idea why Travis is not building on my branch. Anyone else know?

**Comment by spacerockzero** [comment]
This looks legit from my eyeball review. Hard to say why this wasn't addressed for so long before. I will test it more today, and hopefully get it merged soon.

**Comment by intervalia** [comment]
I think the main reason we have not seen it yet is because we tend to not have the ' \ ' in HTML. We do have the' / ' all over the place.

I found it because I was using a 'pattern' attribute for the <input> tag and it uses JavaScript RegExp. I needed to use  "\d"

It was then that I saw the bug.

Mike

**Comment by spacerockzero** [comment]
testing locally now
then i will test it on a reference deploy

**Comment by spacerockzero** [comment]
This seemed to work locally, and when deployed to beta. I will merge it, unless @redbugz has any issues with it.

**Comment by intervalia** [comment]
Thanks Jakob.

**Pull request merged**
