### PR TITLE
Taas Integration - Part 1 - Javascript

### PR DESCRIPTION
**Pull request by rosemariesadler**
Adding check for taasEx app setting sent from snow. If it's turned on, it writes the necessary functions to the assembly file to use TaaS. Default behavior doesn't change.

### CODE REVIEW

**Comment by rosemariesadler** [comment]
It looks like the checks failed because Travis CI's user doesn't have access to fs-webdev/taas-client. What can I do to fix that?

**Comment by spacerockzero** [comment]
This PR looks good. 
BTW: Public Travis-CI can't install anything with private github repos, so Rose is planning to split TaaS into a public and private part, so the public part can be a dep of AM, and then the Travis-CI tests should work again.

**Comment by redbugz** [comment]
Is there a way to avoid having asset-manager depend on TaaS at all? Can it be passed in at runtime via config?

**Comment by rosemariesadler** [comment]
The public repo is now used in this PR and the checks are passing here. I'll unpin the branch on the next update. @redbugz: What would be the advantage of passing it in via config vs having a dependency?

**Comment by rosemariesadler** [comment]
@redbugz Is this PR good to merge?

**Comment by redbugz** [comment]
I think I'd like to get away from having the assembly manage the translations, which limits our ability to use this outside of assemblies. I was thinking that this would belong on the FS object instead, which also helps us get away from translations being tied to the view/file and be more logically scoped.

**Comment by rosemariesadler** [comment]
So maybe, this PR should be closed, and nothing will change in asset manager. Then, in the _translations partial in theme engage, i18n should be added it to the FS object. So then on the client side you would always have to use FS.i18n(key, options). Is that what you're thinking?

**Comment by rosemariesadler** [comment]
Currently, how do you use translations outside of assemblies?

**Comment by redbugz** [comment]
You have to build your own thing, we don't provide any support outside of assemblies, which is not good. So we wanted the new thing to not be tied to assemblies if we can avoid it.

**Comment by rosemariesadler** [comment]
Then FS.i18n(key, options) is probably the way to do it. I'll make those changes and update my theme-engage PR. It will also require another snow PR.

**Pull request closed without merging**
