### PR TITLE
Js attributes

### PR DESCRIPTION
**Pull request by lambertsteven**

### CODE REVIEW

**Comment by lambertsteven** [comment]
@intervalia were you able to get this working?

**Comment by intervalia** [comment]
From first glance this looks fine. @spacerockzero and @waaronking, how does this look to you?

Mike

**Comment by spacerockzero** [comment]
I would like to test this locally first, then probably push the reference app to beta pinned to this branch of asset manager, and a couple test pages that should thoroughly target all aspects of this new behavior, as well as the old behavior

**Comment by lambertsteven** [comment]
@waaronking I can't remember, did you test this on an app? We're we ok to pull this?

**Comment by spacerockzero** [comment]
I would still want to test it with the above process i mentioned ^^. I am available to do that this afternoon

**Comment by waaronking** [comment]
@lambertsteven Yes, I tested it on home. It worked great for everything I tested it against.

**Comment by spacerockzero** [comment]
because it is ingested by all apps, it potentially affects all of our users, so we should be more dilligent

**Comment by spacerockzero** [comment]
I just tested it on photos app locally, it worked exactly as described, and laid down the proper attributes, and they worked as their api's described.
I am good with this now.

**Pull request merged**
